language: objective-c
osx_image: xcode7.2
script:
  - xctool -workspace HeyHere.xcworkspace -scheme HeyHere -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace HeyHere.xcworkspace -scheme HeyHereTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
before_script:
  - chmod a+x ./scripts/add-key.sh
  - sh ./scripts/add-key.sh
