platform:ios,'7.0'
pod 'FMDB','~>2.5'
pod 'CocoaLumberjack','~>2.0.0'
pod 'ASValueTrackingSlider','~>0.11.2'
pod 'Masonry','~>0.6.4'
pod 'PSTAlertController', '~>1.2.0'
pod 'Fabric'
pod 'Crashlytics'
